---
# Organization to pull metrics from
organization: 'openfoodfacts'

# Start date to pull metrics from
since: '2014-11-01'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/org-metrics-dashboard'
